version: "3.3"
services:
  mongodb:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
  messenger-api:
    build: .
    restart: always
    environment:
      spring.data.mongodb.host: mongodb
    ports:
      - 8080:8080
    links:
      - mongodb